name: CI Build & Push Docker

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/deployment.yaml'

permissions:
  contents: write

env:
  IMAGE_NAME: demo-backend

jobs:
  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
         fetch-depth: 0
         token: ${{ secrets.GIT_TOKEN }}

      # 5. Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 6. Login to ACR
      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      # 7. Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      # 8. Push Docker image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update Deployment YAML
        run: |
          sed -i "s|image: ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:.*|image: ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" k8s/deployment.yaml

      - name: Commit & Push Deployment Update
        run: |
          git config user.email "ci-bot@example.com"
          git config user.name "CI Bot"
          git add k8s/deployment.yaml
          git commit -m "Update deployment to image ${{ github.sha }}"
          git push

