name: CI Build & Push Docker

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: demo-backend

jobs:
  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 5. Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 6. Login to ACR
      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      # 7. Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      # 8. Push Docker image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
